- adjusted client download script and tarball generator
--HG--
extra : convert_revision : 3b24e4fc26a1bf266f968305b009933ef5389122

diff --git a/client/remuco-download-client b/client/remuco-download-client
--- a/client/remuco-download-client
+++ b/client/remuco-download-client
@@ -28,13 +28,16 @@
 # where the actual client binary files are not supposed to be in the
 # repositories.
 
-VERSION=0.9.0
-PKG=remuco-$VERSION
+VERSION=0.9.1
+PKG=remuco-client-$VERSION
 TARBALL=$PKG.tar.gz
 URL=http://downloads.sourceforge.net/remuco/$TARBALL
 
 die() {
 	echo "$1"
+	echo
+	echo "Try again or get the client manually from:"
+	echo "$URL"
 	exit 1
 }
 
@@ -51,23 +54,22 @@ EOF
 
 read INPUT
 
-echo "Remove old temporary files ..."
-rm -rf /var/tmp/$TARBALL /var/tmp/$PKG || die "failed"
+echo "Removing old temporary files ..."
+rm -rf /var/tmp/$TARBALL /var/tmp/$PKG || die "Failed :("
 
 echo "Downloading tarball ..."
-wget $URL -O /var/tmp/$TARBALL || die "failed" 
+wget $URL -O /var/tmp/$TARBALL || die "Failed :(" 
 
 echo "Unpacking tarball ..."
-tar zxf /var/tmp/$TARBALL -C /var/tmp/ || die "failed"
+tar zxf /var/tmp/$TARBALL -C /var/tmp/ || die "Failed :("
 
 cat << EOF
 -------------------------------------------------------------------------------
-Done.
+Done. The client files to install on your mobile device are located in
+'/var/tmp/$PKG/'. Trying to open a file browser ..
 
-The client files to install on your mobile device are located in:
-/var/tmp/$PKG/client/app/
-
-For more information visit:
-http://remuco.sourceforge.net/index.php/Getting_Started 
--------------------------------------------------------------------------------
 EOF
+
+sleep 1
+
+xdg-open /var/tmp/$PKG/ &
